runtime: nodejs16

env_variables:
  PORT: 8080
  OLD_CLIENT_ID: 865875845493-9djviph0sdv3mulhko1afchne7ipg92d.apps.googleusercontent.com
  OLD_CLIENT_SECRET: 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
  OLD_REFRESH_TOKEN: 1//0466LAuRXON4VCgYIARAAGAQSNwF-L9Irp68pk0uTxql-eUx69v_HzzgnHip0p-kHsYfyCcsR2zgsStmgwEf4uN61RsEOCyeL7r8
  CLIENT_ID: 735899950129-5f1pi6ckmmasnnc7q9o31bi6rrrptl5i.apps.googleusercontent.com
  CLIENT_SECRET: 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
  REFRESH_TOKEN: 1//046gb_muWftlBCgYIARAAGAQSNwF-L9IrMppnZ_Uidxosik7fELOGNwSYAg67ChGksE23y5iflQ534gA3tokPUVMb0YMTAMsWjkA
  REDIRECT_URL: https://developers.google.com/oauthplayground
  EMAIL: services@jacykdev.com